import { repeat } from './utilities'

function makeNoteDom(a,b,c){var d=document.createElement("div");a=document.createTextNode(a);d.appendChild(a);a=document.createElement("div");b=document.createTextNode(b);a.appendChild(b);b=document.createElement("div");b.appendChild(d);b.appendChild(a);c.appendChild(b)}function makeNotes(a,b){for(var c=0;c<a.length;c++)makeNoteDom(a[c].title,a[c].content,b)}
function main(){var a=document.getElementById("notes");makeNotes([{title:"Note 1",content:"Content of Note 1"},{title:"Note 2",content:"Content of Note 2"}],a)}main();
// Input 1
var rules$$module$Input_0={paragraph:{filter:"p",replacement:function(a){return"\n\n"+a+"\n\n"}},lineBreak:{filter:"br",replacement:function(a,b,c){return c.br+"\n"}},heading:{filter:"h1 h2 h3 h4 h5 h6".split(" "),replacement:function(a,b,c){b=Number(b.nodeName.charAt(1));return"setext"===c.headingStyle&&3>b?(c=repeat(1===b?"=":"-",a.length),"\n\n"+a+"\n"+c+"\n\n"):"\n\n"+repeat("#",b)+" "+a+"\n\n"}},blockquote:{filter:"blockquote",replacement:function(a){a=a.replace(/^\n+|\n+$/g,"");a=a.replace(/^/gm,
"> ");return"\n\n"+a+"\n\n"}},list:{filter:["ul","ol"],replacement:function(a,b){var c=b.parentNode;return"LI"===c.nodeName&&c.lastElementChild===b?"\n"+a:"\n\n"+a+"\n\n"}},listItem:{filter:"li",replacement:function(a,b,c){a=a.replace(/^\n+/,"").replace(/\n+$/,"\n").replace(/\n/gm,"\n    ");var d=c.bulletListMarker+"   ";c=b.parentNode;"OL"===c.nodeName&&(d=c.getAttribute("start"),c=Array.prototype.indexOf.call(c.children,b),d=(d?Number(d)+c:c+1)+".  ");return d+a+(b.nextSibling&&!/\n$/.test(a)?"\n":
"")}},indentedCodeBlock:{filter:function(a,b){return"indented"===b.codeBlockStyle&&"PRE"===a.nodeName&&a.firstChild&&"CODE"===a.firstChild.nodeName},replacement:function(a,b,c){return"\n\n    "+b.firstChild.textContent.replace(/\n/g,"\n    ")+"\n\n"}},fencedCodeBlock:{filter:function(a,b){return"fenced"===b.codeBlockStyle&&"PRE"===a.nodeName&&a.firstChild&&"CODE"===a.firstChild.nodeName},replacement:function(a,b,c){a=((b.firstChild.getAttribute("class")||"").match(/language-(\S+)/)||[null,""])[1];
b=b.firstChild.textContent;c=c.fence.charAt(0);for(var d=3,e=new RegExp("^"+c+"{3,}","gm"),f;f=e.exec(b);)f[0].length>=d&&(d=f[0].length+1);c=repeat(c,d);return"\n\n"+c+a+"\n"+b.replace(/\n$/,"")+"\n"+c+"\n\n"}},horizontalRule:{filter:"hr",replacement:function(a,b,c){return"\n\n"+c.hr+"\n\n"}},inlineLink:{filter:function(a,b){return"inlined"===b.linkStyle&&"A"===a.nodeName&&a.getAttribute("href")},replacement:function(a,b){var c=b.getAttribute("href"),d=cleanAttribute$$module$Input_0(b.getAttribute("title"));
d&&(d=' "'+d+'"');return"["+a+"]("+c+d+")"}},referenceLink:{filter:function(a,b){return"referenced"===b.linkStyle&&"A"===a.nodeName&&a.getAttribute("href")},replacement:function(a,b,c){var d=b.getAttribute("href");(b=cleanAttribute$$module$Input_0(b.getAttribute("title")))&&(b=' "'+b+'"');switch(c.linkReferenceStyle){case "collapsed":c="["+a+"][]";a="["+a+"]: "+d+b;break;case "shortcut":c="["+a+"]";a="["+a+"]: "+d+b;break;default:var e=this.references.length+1;c="["+a+"]["+e+"]";a="["+e+"]: "+d+b}this.references.push(a);
return c},references:[],append:function(a){a="";this.references.length&&(a="\n\n"+this.references.join("\n")+"\n\n",this.references=[]);return a}},emphasis:{filter:["em","i"],replacement:function(a,b,c){return a.trim()?c.emDelimiter+a+c.emDelimiter:""}},strong:{filter:["strong","b"],replacement:function(a,b,c){return a.trim()?c.strongDelimiter+a+c.strongDelimiter:""}},code:{filter:function(a){var b=a.previousSibling||a.nextSibling;b="PRE"===a.parentNode.nodeName&&!b;return"CODE"===a.nodeName&&!b},
replacement:function(a){if(!a)return"";a=a.replace(/\r?\n|\r/g," ");for(var b=/^`|^ .*?[^ ].* $|`$/.test(a)?" ":"",c="`",d=a.match(/`+/gm)||[];-1!==d.indexOf(c);)c+="`";return c+b+a+b+c}},image:{filter:"img",replacement:function(a,b){var c=cleanAttribute$$module$Input_0(b.getAttribute("alt")),d=b.getAttribute("src")||"",e=cleanAttribute$$module$Input_0(b.getAttribute("title"));return d?"!["+c+"]("+d+(e?' "'+e+'"':"")+")":""}}};
function cleanAttribute$$module$Input_0(a){return a?a.replace(/(\n+\s*)+/g,"\n"):""}var $jscompDefaultExport$$module$Input_0=rules$$module$Input_0,module$Input_0={};module$Input_0["default"]=$jscompDefaultExport$$module$Input_0;